# Generated by Django 5.0.4 on 2024-05-02 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id сессии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('TRANSFER_TO_ACCOUNT', 'Перевод на счет')], default='TRANSFER_TO_ACCOUNT', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
