# Generated by Django 5.0.4 on 2024-04-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-name'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
