# Generated by Django 5.0.4 on 2024-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
